app:
  is_master: true
  workdir: ./test
server:
  addr: 0.0.0.0:2345
docker:
  host: unix:///var/run/docker.sock
logger:
  file:
    path: ./logs
    name: server.log
    level: info
    max_size: 100
    max_age: 30
    max_backups: 3
  console:
    level: debug
    format: text
    color: true
  gorm:
    level: debug
    slow_threshold: 200ms
    caller: true
    ignore_record_not_found_error: false