basePath: /api/v1
host: localhost:2345
info:
  contact:
    email: dev_support@gail.com
    name: 服务支持
    url: https://pangud.org
  description: PANGUD OS API.
  license:
    name: AGPL-3.0
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
  termsOfService: https://pangud.org
  title: PangudOS API
  version: "1.0"
paths:
  /ssl_certs/dns_providers:
    get:
      consumes:
      - application/json
      description: 查询DNS提供商列表
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 查询DNS提供商列表
      tags:
      - SSL证书
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
